name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    default:
    type: string
  llvm-version:
    description: 'LLVM version to use.'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
      SUBDIR: ${{ inputs.subdir }}
      LLVM_VERSION: ${{ inputs.llvm-version }}
    run: |
      set -euxo pipefail

      K_VERSION=$(cat ${SUBDIR}deps/k_release)

      docker build . --file ${SUBDIR}.github/workflows/Dockerfile    \
          --tag pi2/${TAG_NAME}                                      \
          --build-arg LLVM_VERSION=${LLVM_VERSION}                   \
          --build-arg K_VERSION=${K_VERSION}                         \
          --build-arg USER=$(id -un) --build-arg USER_ID=$(id -u)    \
          --build-arg GROUP=$(id -gn) --build-arg GROUP_ID=$(id -g)

      docker run                             \
          --name ${TAG_NAME}                 \
          --rm -it                           \
          --detach                           \
          --workdir /opt/workspace/${SUBDIR} \
          --user $(id -un):$(id -gn)         \
          -v "$(pwd):/opt/workspace"         \
          -v "/etc/passwd:/etc/passwd:ro"    \
          -v "/etc/group:/etc/group:ro"      \
          pi2/${TAG_NAME}
